### ISSUE TITLE
Developer Page Images not in middle

### ISSUE THREAD

**Issue by Kartik-3004** [devlup-labs/hms-iitj#10]
Go to - http://hc.iitj.ac.in/developers/
The image of the mentor is not in the middle.
The problem persists in desktop view.
Attaching screenshot for reference.
![image](https://user-images.githubusercontent.com/62802063/95415243-5ea5fb80-094d-11eb-9448-79711649db44.png)

**Comment by harsh-not-haarsh** [comment]
@Kartik-3004 The screenshots are visible.

**Comment by harsh-not-haarsh** [comment]
Duplicate with #9
