### ISSUE TITLE
A few Frontend Issues

### ISSUE THREAD

**Issue by Jashpatel1** [devlup-labs/hms-iitj#11]
- [ ] Change the title of page to a more relevant one, currently its "IIT Jodhpur". Possible titles could be "HC - IITJ" or "HC- IIT Jodhpur"

- [ ] The double quotes seem to move out of screen
![Capture11](https://user-images.githubusercontent.com/43696490/95415064-f6571a00-094c-11eb-83a2-7a488aa56f14.JPG)

- [ ] On hovering to make appointment, the cursor dosent change
![Capture](https://user-images.githubusercontent.com/43696490/95415068-f820dd80-094c-11eb-8a01-94eba678c840.JPG)

- [ ] A bottom-padding can be added in blogs list
![image](https://user-images.githubusercontent.com/43696490/95415856-007a1800-094f-11eb-8af4-544ea9bd0fef.png)

**Comment by pablowbk** [comment]
Hi! I can work on these, would you please assign the issue to me?

**Comment by pablowbk** [comment]
is this site live? could you please provide more details on how to get the local env running?
I fixed all issues except the double quotes

**Comment by pablowbk** [comment]
would you rather a fade-out effect for the blog posts preview?
![image](https://user-images.githubusercontent.com/36734796/95731048-661f1a80-0c55-11eb-9a26-a8a954904ed7.png)

or a cleaner look?
![image](https://user-images.githubusercontent.com/36734796/95731254-a8e0f280-0c55-11eb-965b-13a62064ac4b.png)

**Comment by pablowbk** [comment]
What was the idea with the quotes? I've placed it closer to the text, but I am not sure about what was intended with these:

![image](https://user-images.githubusercontent.com/36734796/95736824-1fcdb980-0c5d-11eb-8294-feddfe990e2a.png)

**Comment by harsh-not-haarsh** [comment]
@pablowbk A cleaner look would be better for blog post, also I think we can get rid of the quotes?

**Comment by pablowbk** [comment]
@harsh-not-haarsh noted. I've closed the existing PR, will push a new one with these suggestions in mind. Thanks
