### ISSUE TITLE
Heading not visible in the Facilities section.

### ISSUE THREAD

**Issue by Kartik-3004** [devlup-labs/hms-iitj#13]
Go to - http://hc.iitj.ac.in
Open it in mobile view.

DESCRIPTION
In the facilities page. The letter 's' in facilities is being cut by the image making it look little weird.

The problem exists in mobile view.

Attaching screenshot for reference -->
![image](https://user-images.githubusercontent.com/62802063/95415929-2c959900-094f-11eb-9e69-d764ef330579.png)

**Comment by saidau** [comment]
Hi,
Is it acceptable for you to have a background image 100% width on mobile and title 'Facilities' to have white color to improve visibility?
If yes, can you assign ticket to me please?

**Comment by harsh-not-haarsh** [comment]
Yeah, that should work.

**Comment by SaurabhModi26** [comment]
i think do font size 42px and we are good to go

**Comment by SaurabhModi26** [comment]
> i think do font size 42px and we are good to go

I realized after seeing many views that pixel unit will not work for this responsiveness issue. So I have tried to fix it by using em unit to make it mobile responsive. I am doing one more pull request with screenshots attached to it.

**Comment by SaurabhModi26** [comment]
here are the screenshots for various different Mobile views
![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_12_00](https://user-images.githubusercontent.com/76422273/109248632-2889eb00-780c-11eb-8873-14b55d7371a1.png)

![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_11_55](https://user-images.githubusercontent.com/76422273/109248672-3b9cbb00-780c-11eb-91bd-0027ab72d731.png)

![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_11_48](https://user-images.githubusercontent.com/76422273/109248686-435c5f80-780c-11eb-8078-6f11a8bb15e7.png)

![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_11_42](https://user-images.githubusercontent.com/76422273/109248703-49ead700-780c-11eb-9010-f8c7d1eb3d06.png)

![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_11_36](https://user-images.githubusercontent.com/76422273/109248714-51aa7b80-780c-11eb-9e94-ba031c67ae43.png)

![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_11_26](https://user-images.githubusercontent.com/76422273/109248732-596a2000-780c-11eb-8e37-2ebf0a14dcb6.png)

![IIT Jodhpur - Hospital Management System - Google Chrome 26-02-2021 08_11_18](https://user-images.githubusercontent.com/76422273/109248750-625af180-780c-11eb-9c54-456090b58fe6.png)

**Comment by harsh-not-haarsh** [comment]
Hey @SaurabhModi26 
You should attach the screenshots in the PR, not the issue.

**Comment by SaurabhModi26** [comment]
ok sorry for that

> Hey @SaurabhModi26
> You should attach the screenshots in the PR, not the issue.

sorry for that
