### ISSUE TITLE
background image dimensions

### ISSUE THREAD

**Issue by Kartik-3004** [devlup-labs/hms-iitj#14]
Go to - http://hc.iitj.ac.in

The background image is not occupying the complete screen size. There is some white space left at the bottom which doesn't look aesthetically pleasing.

Attaching screenshot for reference -->
![image](https://user-images.githubusercontent.com/62802063/95416521-99f5f980-0950-11eb-8f5b-9b05947a9342.png)

**Comment by harsh-not-haarsh** [comment]
It shouldn't be the case.
I think this is due to either of two reasons, 

1. There could have been downloads at the bottom (that we later crossed)

2. There was a success/failure message at the top.

Can you refresh the tab and see if the issue persists?

**Comment by Kartik-3004** [comment]
Yes the issue still persists.

**Comment by harsh-not-haarsh** [comment]
Hmm, got it. The issue occurs when the screen is taller than it is wide.
![image](https://user-images.githubusercontent.com/44001232/95417561-fce89000-0952-11eb-8861-c916f2c89fc8.png)
![image](https://user-images.githubusercontent.com/44001232/95417652-328d7900-0953-11eb-81ba-de48617243c5.png)

**Comment by Kartik-3004** [comment]
If you login then the success message is shown only the first time and after that if you press Home button or go to some other page and return back to home page the success message is gone. However even when the success message is there the problem still persists.

Attaching screenshot for reference -->
![image](https://user-images.githubusercontent.com/62802063/95417815-9748d380-0953-11eb-887d-2301797dfed4.png)

**Comment by harsh-not-haarsh** [comment]
@killbotXD Perhaps you might be able to help here?

**Comment by killbotXD** [comment]
> Go to - http://hc.iitj.ac.in
> 
> The background image is not occupying the complete screen size. There is some white space left at the bottom which doesn't look aesthetically pleasing.
> 
@Kartik-3004 
I don't think there is a way to replicate this issue just by going to hc.iitj.ac.in. what are your screen dimensions? I think you may have accidentally zoomed in. Can you check that too?

**Comment by killbotXD** [comment]
@harsh probably because of this `hero-slider` class [here](https://github.com/devlup-labs/hms-iitj/blob/648d6f07465570164949983bd319b2abf5acde02/templates/main/index.html#L7) that restricts the max height to 950px or so whereas for the background image, the project dynamically calculates the height according to the viewport size. Remove the class and you would be good to go :)

**Comment by Kartik-3004** [comment]
> > Go to - http://hc.iitj.ac.in
> > The background image is not occupying the complete screen size. There is some white space left at the bottom which doesn't look aesthetically pleasing.
> 
> @Kartik-3004
> I don't think there is a way to replicate this issue just by going to hc.iitj.ac.in. what are your screen dimensions? I think you may have accidentally zoomed in. Can you check that too?

**Comment by Kartik-3004** [comment]
Sorry I bymistakely closed it.

**Comment by Kartik-3004** [comment]
@killbotXD I checked it is not zoomed.

**Comment by killbotXD** [comment]
yeah figured the problem out here

> @harsh probably because of this `hero-slider` class [here](https://github.com/devlup-labs/hms-iitj/blob/648d6f07465570164949983bd319b2abf5acde02/templates/main/index.html#L7) that restricts the max height to 950px or so whereas for the background image, the project dynamically calculates the height according to the viewport size. Remove the class and you would be good to go :)

**Comment by SaurabhModi26** [comment]
is this issue closed?

**Comment by harsh-not-haarsh** [comment]
negative
