### ISSUE TITLE
Inconsistent Design

### ISSUE THREAD

**Issue by killbotXD** [devlup-labs/hms-iitj#9]
The website follows a curvy design whereas the blog cards don't which creates an inconsistency in the design, similarly with some buttons on the homepage and the profile view/edit page.
What is required is to make the design consistent i.e. 

### Tasks
+ add border radius to the blog cards and also make sure that all the cards/buttons have the same border radius.
![hc1](https://user-images.githubusercontent.com/42870378/94516948-9b367080-0244-11eb-829b-75e5a591e148.jpg)

+ The button on the `profile-edit/view` page is also inconsistent in terms of color(hover and non hover) make that consistent too 
![hc2](https://user-images.githubusercontent.com/42870378/94517156-f2d4dc00-0244-11eb-8df9-21219c217e5e.jpg) ![hc3](https://user-images.githubusercontent.com/42870378/94517166-f9635380-0244-11eb-8d63-7670d1e0391c.jpg)

+ The footer at the `History`  page is also inconsistent with the design change the text color to make it consistent
+ Mentor Image on `Developers` page is not centered horizontally add `mx-auto` to the image classes(not the parent div) instead of `justify-content-center` or any other means to bring it in the center of the page
![dc5](https://user-images.githubusercontent.com/42870378/94517504-b2c22900-0245-11eb-80b0-c9776422ca56.jpg)

+ There is an unnecessary padding in the `team-section` of the `Developers` page in mobile view, only the top padding is necessary(not too much around 80px), remove the others.
![dc6](https://user-images.githubusercontent.com/42870378/94517696-1a787400-0246-11eb-8ea9-9a369354e5d5.jpg)

**Comment by Hiteshkrkumawat** [comment]
I will take care of this issue

**Comment by evi1haxor** [comment]
Additionally, the font style of `class="footer_title text-center"` does not seem to concur with the overall typography of the page. You may want to make that consistent too.

**Comment by harsh-not-haarsh** [comment]
@evi1haxor Certainly

**Comment by killbotXD** [comment]
@Hiteshkrkumawat any progress?

**Comment by SaurabhModi26** [comment]
harsh i manipulated border-radius to 20px and padding of "edit" to 10px.
